namespace Server.Game;

public class BasicProjectile : Projectile { }
public class BasicProjectile2 : Projectile { }
public class BlossomDeathProjectile : Projectile { }
public class BlossomProjectile : Projectile { }
public class BombProjectile : Projectile { }
public class MosquitoPesterProjectile : Projectile { }
public class MosquitoStingerProjectile : Projectile { }
public class SeedProjectile : Projectile { }
public class SnakeFire : Projectile { }
public class SnakeNagaFire : Projectile { }
public class SnakeNagaBigFire : Projectile { }
public class SmallPoison : Projectile { }
public class BigPoison : Projectile { }
public class BasicProjectile3 : Projectile { }
public class BasicProjectile4 : Projectile { }
public class RabbitAggro : Projectile { }
public class HarePunch : Projectile { }
public class Sprout3HitFire : SproutFire { }
public class SoulProjectile : Projectile { }
public class FungiProjectile : Projectile { }
public class ToadstoolProjectile : Projectile { }
public class HauntFire : Projectile { }
public class HauntProjectile : Projectile { }
public class SunfloraPixieFire : Projectile { }
public class SunfloraPixieProjectile : Projectile { }
public class HermitProjectile : Projectile { }
public class SoulMageProjectile : Projectile { }
public class SpikeProjectile : Projectile { }
public class SkeletonMageProjectile : Projectile { }
public class MothMoonProjectile : Projectile { }
public class MothCelestialPoison : Projectile { }
