namespace Server.Game;

public class PoisonBombExplosion : Effect { }
public class PoisonBombSkillExplosion : Effect{ }
public class SnowBombExplosion : Effect { }
public class BombSkillExplosion : Effect { }
public class StateHeal : Effect { }
public class StatePoison : Effect { }
public class StateAggro : Effect { }
public class StateBurn : Effect { }
public class StateCurse : Effect { }
public class StateDebuffRemove : Effect { }
public class StateFaint : Effect { }
public class StateSlow : Effect { }
public class HolyAura : Effect { }
public class UpgradeEffect : Effect { }
public class WolfMagicalEffect : Effect { }
public class WerewolfMagicalEffect : Effect { }
public class HorrorRoll : Effect { }
public class CactusBossBreathEffect : Effect { }
public class CactusBossSmashEffect : Effect { }
public class LightningStrike : Effect { }
public class SkeletonEffect : Effect { }
public class SkeletonAdditionalEffect : Effect { }
public class SkeletonGiantEffect : Effect { }
public class SkeletonGiantSkill : Effect { }
public class WillRevive : Effect { }
public class HareEffect : Effect { }
public class HareCloneEffect : Effect { }
public class StarFall : Effect { }
public class HermitRecoverBurn : Effect { }
public class MoveForwardEffect : Effect { }
public class WindRoadEffect1 : Effect { }
public class WindRoadEffect2 : Effect { }
public class WindRoadEffect3 : Effect { }
public class WindRoadEffect4 : Effect { }
public class WindRoadEffect5 : Effect { }
public class FireRoadEffect1 : Effect { }
public class FireRoadEffect2 : Effect { }
public class FireRoadEffect3 : Effect { }
public class FireRoadEffect4 : Effect { }
public class FireRoadEffect5 : Effect { }
public class EarthRoadEffect1 : Effect { }
public class EarthRoadEffect2 : Effect { }
public class EarthRoadEffect3 : Effect { }
public class EarthRoadEffect4 : Effect { }
public class EarthRoadEffect5 : Effect { }